### ISSUE TITLE
Slight typo

### ISSUE THREAD

**Issue by oldergod** [dentex/piac#1]
Hello!

Please ignore the title. Your github website is gone and I was wondering if everything was alright for you? I've been using ydownloader for many years now and always wanted to say thank you. So thank you!

**Comment by dentex** [comment]
Wow, a GitHub issue for that! 

Jokes aside, a proper landing page instead of a 404  is due since a long time... I'm answering to lot of emails lately.

Thanks for the interest: yeah I'm ok. The app is not.

Last year I had to stop the development of the app (mainly for personal reasons) and thus it's no longer available on my blog (I took it down too). Now it seems it's not even working anymore. I'm sorry for any inconvenience this may cause. 

For an alternative, take a look at NewPipe. It's an open source and actively developed app for android. It's not available on the play store, but you can find it on GitHub or on their website https://newpipe.net/
